/**
 * WebSocket frame type definitions for the Realtime Gateway — WO-069 extended.
 *
 * Server → client frames carry type, tenantId, seq, prevSeq and generatedAt.
 * Client → server messages are subscribe (with optional lastSeq) and pong.
 *
 * Wire-format changes (WO-069):
 *  - BaseServerFrame gains prevSeq and generatedAt (set by the publisher).
 *  - SnapshotFrame added for full-state delivery (type 'snapshot').
 *  - SnapshotRequiredFrame gains typed `reason` field.
 *  - SubscribeMessage.lastSeq is now `number | null` (null on first connect).
 *  - RedisPublishPayload updated to match the new publisher output shape.
 */

// ---------------------------------------------------------------------------
// Principal stored per socket
// ---------------------------------------------------------------------------

export interface SocketPrincipal {
  sub: string;
  tenantId: string;
  roles: string[];
  orgScopeVersion: number;
  /** Set of organisation UUIDs the principal may see. Empty = all (manager/admin). */
  orgScopeIds: Set<string>;
  userType: string;
}

// ---------------------------------------------------------------------------
// Per-socket wrapper stored in the registry
// ---------------------------------------------------------------------------

export interface SocketWrapper {
  /** The raw ws socket. */
  ws: import('ws').WebSocket;
  /** Authenticated principal. */
  principal: SocketPrincipal;
  /** Last seq delivered to this socket. */
  lastDeliveredSeq: number;
  /** Monotonic timestamp of last pong (performance.now()). */
  lastPongAt: number;
  /** True after subscribe message received. */
  subscribed: boolean;
  /** True while backfill is in progress — live frames buffered in outbound queue. */
  backfilling: boolean;
}

// ---------------------------------------------------------------------------
// Server → client frames
// ---------------------------------------------------------------------------

export interface BaseServerFrame {
  type: string;
  tenantId: string;
  seq: number;
  /** Previous seq this frame follows; 0 on the first frame. */
  prevSeq: number;
  /** ISO-8601 timestamp when the frame was generated by the publisher. */
  generatedAt: string;
  sentAt: string; // ISO-8601 timestamp when the gateway sent the frame
}

export interface HelloFrame extends Omit<BaseServerFrame, 'prevSeq' | 'generatedAt'> {
  type: 'hello';
  prevSeq: 0;
  generatedAt: string;
  payload: Record<string, never>;
}

// KPI delta payload (from WO-069 delta publisher)
export interface KpiDelta {
  [field: string]: number;
}

export interface CategoryDeltaEntry {
  categoryPath: string;
  count: number;
}

export interface AffectedAreaDeltaEntry {
  areaTag: string;
  count: number;
}

export interface BreachRiskRow {
  ticketId: string;
  nextFireAt: number;
}

export interface WireDeltaPayload {
  kpis?: KpiDelta;
  categoryDelta?: CategoryDeltaEntry[];
  affectedAreaDelta?: AffectedAreaDeltaEntry[];
  breachRiskAdded?: BreachRiskRow[];
  breachRiskRemoved?: string[];
  feedAppended?: string[];
}

export interface WireSnapshotPayload {
  kpis: Record<string, number>;
  category: Array<{ category: string; count: number }>;
  affectedArea: Array<{ area: string; count: number }>;
  breachRisk: Array<{ ticketId: string; nextFireAt: number }>;
  feed: string[];
}

export interface DeltaFrame extends BaseServerFrame {
  type: 'delta';
  payload: WireDeltaPayload;
}

export interface SnapshotFrame extends BaseServerFrame {
  type: 'snapshot';
  payload: WireSnapshotPayload;
}

// Legacy shape kept for backward compat with existing OrgBreakdown DeltaPayload
export interface OrgBreakdownItem {
  organizationId: string;
  counters: Record<string, number>;
}

export interface LegacyDeltaPayload {
  globalCounters: Record<string, number>;
  orgBreakdown: OrgBreakdownItem[];
}

// Reason codes for snapshot_required
export type SnapshotRequiredReason =
  | 'seq_out_of_window'
  | 'invalid_seq'
  | 'slow_consumer'
  | 'redis_reset';

export interface SnapshotRequiredFrame {
  type: 'snapshot_required';
  tenantId: string;
  reason: SnapshotRequiredReason;
}

export interface GoingAwayFrame extends BaseServerFrame {
  type: 'going_away';
  payload: { reconnectAfterMs: number };
}

export interface ErrorFrame extends BaseServerFrame {
  type: 'error';
  payload: { code: string; message: string };
}

export type ServerFrame =
  | HelloFrame
  | DeltaFrame
  | SnapshotFrame
  | SnapshotRequiredFrame
  | GoingAwayFrame
  | ErrorFrame;

// ---------------------------------------------------------------------------
// Client → server messages
// ---------------------------------------------------------------------------

export interface SubscribeMessage {
  type: 'subscribe';
  channel: 'dashboard';
  /** null on first connect; number to request backfill from that seq forward. */
  lastSeq: number | null;
}

export interface PongMessage {
  type: 'pong';
}

export type ClientMessage = SubscribeMessage | PongMessage;

// ---------------------------------------------------------------------------
// Redis pub/sub payload (published by workers under dash:{tenantId}) — WO-069
// ---------------------------------------------------------------------------

export interface RedisPublishPayload {
  type: 'delta' | 'snapshot';
  tenantId: string;
  seq: number;
  prevSeq: number;
  generatedAt: string;
  payload: WireDeltaPayload | WireSnapshotPayload;
}
