/**
 * AI Synthesis schema module.
 *
 * Stores LLM-generated ticket summaries and blast-radius tags so the
 * Real-Time Operational Dashboard and the executive report builder can
 * aggregate them from the primary reporting database.
 *
 * Design rules:
 *   - tenant_id leads the composite PK (tenant_id, id) on each table.
 *   - ticket_ai_summaries carries a UNIQUE (tenant_id, ticket_id) so
 *     synthesis writeback is idempotent — upsert targets this constraint.
 *   - ai_status is constrained to: pending | running | succeeded | failed | skipped.
 *     Enforced via SQL CHECK in migration 0060.
 *   - crux_summary and resolution_summary are Confidential tier (PII);
 *     they are excluded from structured log output via the redact allow-list.
 *   - FK to tickets omitted: tickets is range-partitioned with PK
 *     (tenant_id, id, created_at); PostgreSQL cannot reference the full
 *     partition-key PK from a non-partitioned table without created_at.
 *     Cascade delete is handled by the retention purge manifest.
 *     This exception mirrors ticket_comments and is documented in
 *     migrations/README.md.
 */
import {
  integer,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core';
import { tenants } from './tenants.js';

export const ticketAiSummaries = pgTable(
  'ticket_ai_summaries',
  {
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id),
    id: uuid('id').notNull().defaultRandom(),
    ticketId: uuid('ticket_id').notNull(),
    /**
     * crux_summary: Confidential tier — redacted in all structured logs.
     * Length cap applied at write time by the repository (8 000 chars).
     */
    cruxSummary: text('crux_summary'),
    /**
     * resolution_summary: Confidential tier — redacted in all structured logs.
     * Length cap applied at write time by the repository (8 000 chars).
     */
    resolutionSummary: text('resolution_summary'),
    modelId: text('model_id'),
    promptVersion: text('prompt_version'),
    /**
     * ai_status: pending | running | succeeded | failed | skipped.
     * CHECK constraint enforced in SQL migration.
     */
    aiStatus: text('ai_status').notNull().default('pending'),
    /**
     * Durable attempt counter for the three-attempt failure cap.
     * Incremented by the synthesis worker each time it processes this ticket.
     */
    attemptCount: integer('attempt_count').notNull().default(0),
    lastErrorCode: text('last_error_code'),
    generatedAt: timestamp('generated_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    primaryKey({ columns: [table.tenantId, table.id] }),
  ],
);

export const ticketAffectedAreas = pgTable(
  'ticket_affected_areas',
  {
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id),
    id: uuid('id').notNull().defaultRandom(),
    ticketId: uuid('ticket_id').notNull(),
    /**
     * area_label: human-readable blast-radius tag e.g. 'Payments', 'Auth'.
     * Duplicate labels for a given ticket must be de-duplicated before insert.
     */
    areaLabel: text('area_label').notNull(),
    /**
     * confidence: low | medium | high — matches the AffectedAreaChips
     * display in the UI spec. Stored as text to avoid float precision issues.
     */
    confidence: text('confidence'),
    /**
     * source: 'ai' (default) | 'manual' — tracks whether the tag was
     * generated by the model or added by an agent.
     */
    source: text('source').notNull().default('ai'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    primaryKey({ columns: [table.tenantId, table.id] }),
  ],
);

// ---------------------------------------------------------------------------
// Inferred TypeScript types
// ---------------------------------------------------------------------------
export type TicketAiSummary = typeof ticketAiSummaries.$inferSelect;
export type NewTicketAiSummary = typeof ticketAiSummaries.$inferInsert;
export type TicketAffectedArea = typeof ticketAffectedAreas.$inferSelect;
export type NewTicketAffectedArea = typeof ticketAffectedAreas.$inferInsert;

// ---------------------------------------------------------------------------
// Branded status type for compile-time safety
// ---------------------------------------------------------------------------
export const AI_STATUS_VALUES = [
  'pending',
  'running',
  'succeeded',
  'failed',
  'skipped',
] as const;

export type AiStatus = (typeof AI_STATUS_VALUES)[number];

export function isAiStatus(value: unknown): value is AiStatus {
  return typeof value === 'string' && (AI_STATUS_VALUES as readonly string[]).includes(value);
}
