/**
 * Tickets core schema — WO-031.
 *
 * Module ownership: tickets
 * Data classification: Internal (subject, status, priority, custom_fields)
 *
 * Extends the base tickets table defined in schema.ts with all columns
 * required by the ticketing domain plus the SLA, Jira and AI modules.
 *
 * RLS USING/WITH CHECK policies are added in migration 0018_tickets_core.sql.
 * All tables carry tenant_id uuid NOT NULL as the leading column of every
 * composite index so cross-tenant joins are structurally impossible.
 *
 * ticket_number is a per-tenant sequential integer generated by the
 * next_tenant_sequence() PostgreSQL function (via tenant_sequences table).
 * Human display: prefix + ticket_number, e.g. "ON-1042".
 */

import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

// ---------------------------------------------------------------------------
// tickets — core module table
//
// Columns marked "(base)" were already present in the initial schema.ts
// definition from WO-004. WO-031 adds the columns marked "(WO-031)".
// The SQL migration uses ADD COLUMN IF NOT EXISTS so existing rows get safe
// defaults on both old and new columns.
// ---------------------------------------------------------------------------

export const tickets = pgTable(
  'tickets',
  {
    // ── Core identity ─────────────────────────────────────────────────────
    id: uuid('id').defaultRandom().primaryKey(),
    tenantId: uuid('tenant_id').notNull(),

    // ── Relationships ──────────────────────────────────────────────────────
    /** Customer organization that owns the ticket. */
    organizationId: uuid('organization_id').notNull(),

    /** Portal contact who submitted the ticket. Null for agent-created tickets. */
    requesterContactId: uuid('requester_contact_id'),         // WO-031

    /** Staff user currently assigned as the primary responder. */
    assigneeId: uuid('assignee_id'),

    /** Assignment group the ticket belongs to. Null until routed. */
    assignmentGroupId: uuid('assignment_group_id'),           // WO-031

    /** Category FK (category table owned by a future WO). */
    categoryId: uuid('category_id'),                          // WO-031

    // ── Content ────────────────────────────────────────────────────────────
    subject: text('subject').notNull(),
    description: text('description'),                         // WO-031

    // ── State machine ──────────────────────────────────────────────────────
    /**
     * Constrained to 'new' | 'open' | 'pending_customer' | 'pending_engineering'
     * | 'resolved' | 'closed' by a CHECK constraint in the migration.
     * Default kept as 'open' for backward compatibility with base schema rows.
     */
    status: text('status').notNull().default('open'),

    /**
     * P1 = Critical, P2 = High, P3 = Medium (default), P4 = Low.
     * Constrained by CHECK constraint in migration.
     */
    priority: text('priority').notNull().default('P3'),

    // ── Versioning & sequencing ────────────────────────────────────────────
    /**
     * Optimistic-concurrency counter. Every PATCH increments this by 1.
     * WO-033 uses it for 409 responses.
     */
    version: integer('version').notNull().default(1),        // WO-031

    /**
     * Human-readable per-tenant sequence number (e.g. 1042 for ON-1042).
     * Generated by next_tenant_sequence('tickets') trigger on INSERT.
     * Unique per tenant, enforced by unique index.
     */
    ticketNumber: integer('ticket_number'),                   // WO-031

    // ── JSONB extension fields ─────────────────────────────────────────────
    /**
     * Tenant-defined custom field values for ticket metadata.
     * Keys validated against custom_field_defs at application layer.
     * GIN-indexed for containment queries.
     */
    customFields: jsonb('custom_fields').notNull().default({}), // WO-031

    // ── AI-synthesis columns (read by AI worker, not owned by it) ──────────
    /** AI-generated summary populated by the AI Synthesis Worker. */
    aiSummary: text('ai_summary'),

    /**
     * AI processing state: null (not started) | 'pending' | 'processing'
     * | 'complete' | 'failed'.
     */
    aiStatus: text('ai_status'),                              // WO-031

    /** Structured tags from AI affected-area analysis. */
    affectedAreaTags: jsonb('affected_area_tags'),

    // ── Timestamps ─────────────────────────────────────────────────────────
    /**
     * Timestamp of the first public agent reply on this ticket.
     * Set exactly once via conditional UPDATE ... WHERE first_response_at IS NULL.
     * Used by the SLA module to measure time-to-first-response.
     * NULL means no public agent reply has been posted yet. (WO-034)
     */
    firstResponseAt: timestamp('first_response_at', { withTimezone: true }),
    resolvedAt: timestamp('resolved_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    tenantIdx: index('tickets_tenant_id_idx').on(t.tenantId),

    /** Hot queue listing: filter by status/priority, ordered by recency. */
    tenantQueueIdx: index('tickets_tenant_queue_idx').on(
      t.tenantId, t.status, t.priority, t.updatedAt,
    ),

    /** Org-scoped agent queue (e.g. "all open tickets for Acme Corp"). */
    tenantOrgStatusIdx: index('tickets_tenant_org_status_idx').on(
      t.tenantId, t.organizationId, t.status,
    ),

    /** My Assigned Tickets panel. */
    tenantAssigneeStatusIdx: index('tickets_tenant_assignee_status_idx').on(
      t.tenantId, t.assigneeId, t.status,
    ),

    /** Ticket number uniqueness per tenant. */
    tenantTicketNumberUniq: uniqueIndex('tickets_tenant_ticket_number_uniq').on(
      t.tenantId, t.ticketNumber,
    ),
  }),
);

export type Ticket = typeof tickets.$inferSelect;
export type NewTicket = typeof tickets.$inferInsert;

export type TicketStatus =
  | 'new'
  | 'open'
  | 'pending_customer'
  | 'pending_engineering'
  | 'resolved'
  | 'closed';

export type TicketPriority = 'P1' | 'P2' | 'P3' | 'P4';
