/**
 * Schema-level unit tests for the WO-031 ticketing schema — WO-031.
 *
 * Tests run without a database connection: they validate the Drizzle schema
 * object structure (column presence, notNull, defaults) and TypeScript type
 * inference. No network I/O.
 */

import {
  tickets,
  ticketComments,
  ticketAttachments,
  tags,
  ticketTags,
  assignmentGroups,
  assignmentGroupMembers,
  ticketStatusHistory,
  tenantSequences,
} from '../src/schema';

// ---------------------------------------------------------------------------
// Helper: extract Drizzle column map from a pgTable object
// ---------------------------------------------------------------------------

type DrizzleTable = { [key: string]: { notNull?: boolean; hasDefault?: boolean; columnType?: string } };

function cols(table: unknown): DrizzleTable {
  // Drizzle stores columns on the Symbol.for('drizzle:Columns') property or as
  // enumerable string keys depending on the version. Fall back to direct cast.
  return table as DrizzleTable;
}

// ---------------------------------------------------------------------------
// tickets
// ---------------------------------------------------------------------------

describe('tickets schema', () => {
  const t = cols(tickets);

  it('has tenant_id not null', () => {
    expect(t['tenantId']?.notNull).toBe(true);
  });

  it('has organization_id not null', () => {
    expect(t['organizationId']?.notNull).toBe(true);
  });

  it('has subject not null', () => {
    expect(t['subject']?.notNull).toBe(true);
  });

  it('has status not null with default', () => {
    expect(t['status']?.notNull).toBe(true);
    expect(t['status']?.hasDefault).toBe(true);
  });

  it('has priority not null with default', () => {
    expect(t['priority']?.notNull).toBe(true);
    expect(t['priority']?.hasDefault).toBe(true);
  });

  it('has version not null (optimistic concurrency)', () => {
    expect(t['version']?.notNull).toBe(true);
    expect(t['version']?.hasDefault).toBe(true);
  });

  it('has custom_fields not null JSONB', () => {
    expect(t['customFields']?.notNull).toBe(true);
  });

  it('exposes nullable ai_status for AI worker', () => {
    expect(t['aiStatus']?.notNull).toBeFalsy();
  });

  it('exposes nullable ticket_number (generated by trigger)', () => {
    expect(t['ticketNumber']?.notNull).toBeFalsy();
  });
});

// ---------------------------------------------------------------------------
// ticket_comments
// ---------------------------------------------------------------------------

describe('ticket_comments schema', () => {
  const t = cols(ticketComments);

  it('has tenant_id not null', () => {
    expect(t['tenantId']?.notNull).toBe(true);
  });

  it('has ticket_id not null', () => {
    expect(t['ticketId']?.notNull).toBe(true);
  });

  it('has organization_id not null', () => {
    expect(t['organizationId']?.notNull).toBe(true);
  });

  it('has body not null', () => {
    expect(t['body']?.notNull).toBe(true);
  });

  it('has is_internal not null with default false', () => {
    expect(t['isInternal']?.notNull).toBe(true);
    expect(t['isInternal']?.hasDefault).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// ticket_attachments
// ---------------------------------------------------------------------------

describe('ticket_attachments schema', () => {
  const t = cols(ticketAttachments);

  it('has tenant_id not null', () => {
    expect(t['tenantId']?.notNull).toBe(true);
  });

  it('has ticket_id not null', () => {
    expect(t['ticketId']?.notNull).toBe(true);
  });

  it('has filename not null', () => {
    expect(t['filename']?.notNull).toBe(true);
  });

  it('has s3_key not null', () => {
    expect(t['s3Key']?.notNull).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// tags
// ---------------------------------------------------------------------------

describe('tags schema', () => {
  const t = cols(tags);

  it('has tenant_id not null', () => {
    expect(t['tenantId']?.notNull).toBe(true);
  });

  it('has name not null', () => {
    expect(t['name']?.notNull).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// ticket_tags
// ---------------------------------------------------------------------------

describe('ticket_tags schema', () => {
  const t = cols(ticketTags);

  it('has tenant_id not null', () => {
    expect(t['tenantId']?.notNull).toBe(true);
  });

  it('has ticket_id not null', () => {
    expect(t['ticketId']?.notNull).toBe(true);
  });

  it('has tag_id not null', () => {
    expect(t['tagId']?.notNull).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// assignment_groups
// ---------------------------------------------------------------------------

describe('assignment_groups schema', () => {
  const t = cols(assignmentGroups);

  it('has tenant_id not null', () => {
    expect(t['tenantId']?.notNull).toBe(true);
  });

  it('has name not null', () => {
    expect(t['name']?.notNull).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// assignment_group_members
// ---------------------------------------------------------------------------

describe('assignment_group_members schema', () => {
  const t = cols(assignmentGroupMembers);

  it('has tenant_id not null', () => {
    expect(t['tenantId']?.notNull).toBe(true);
  });

  it('has group_id not null', () => {
    expect(t['groupId']?.notNull).toBe(true);
  });

  it('has user_id not null', () => {
    expect(t['userId']?.notNull).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// ticket_status_history
// ---------------------------------------------------------------------------

describe('ticket_status_history schema', () => {
  const t = cols(ticketStatusHistory);

  it('has tenant_id not null', () => {
    expect(t['tenantId']?.notNull).toBe(true);
  });

  it('has ticket_id not null', () => {
    expect(t['ticketId']?.notNull).toBe(true);
  });

  it('has to_status not null', () => {
    expect(t['toStatus']?.notNull).toBe(true);
  });

  it('has nullable from_status (null for initial entry)', () => {
    expect(t['fromStatus']?.notNull).toBeFalsy();
  });
});

// ---------------------------------------------------------------------------
// tenant_sequences
// ---------------------------------------------------------------------------

describe('tenant_sequences schema', () => {
  const t = cols(tenantSequences);

  it('has tenant_id not null', () => {
    expect(t['tenantId']?.notNull).toBe(true);
  });

  it('has sequence_name not null', () => {
    expect(t['sequenceName']?.notNull).toBe(true);
  });

  it('has last_value not null with default 0', () => {
    expect(t['lastValue']?.notNull).toBe(true);
    expect(t['lastValue']?.hasDefault).toBe(true);
  });
});
