/**
 * RLS policy builder — generates idempotent SQL DDL from the table registry.
 *
 * This module exists so that adding a new table to the registry is sufficient
 * to include it in the policy surface; no manual migration edits required for
 * the standard tenant_isolation pattern.
 *
 * Typical usage (e.g. from a CLI tool or drizzle custom migration):
 *
 *   import { buildTenantIsolationSql } from '@opsninja/db/rls/policy-builder';
 *   console.log(buildTenantIsolationSql());
 *
 * Note: portal policies (portal_org_restriction, portal_comment_restriction)
 * require custom USING clauses and are NOT generated by this builder. They are
 * authored manually in 0002_rls.sql and referenced here for documentation only.
 */

import { TENANT_SCOPED_TABLES } from '../schema/table-registry.js';

/** The session variable name used by all tenant isolation policies. */
export const TENANT_SETTING = `current_setting('app.current_tenant', true)::uuid`;

/**
 * USING / WITH CHECK expression shared by all tenant_isolation policies.
 * Returns NULL (falsy) when app.current_tenant is unset — fail-closed.
 */
export const TENANT_PREDICATE = `tenant_id = ${TENANT_SETTING}`;

/**
 * Emits SQL to ENABLE and FORCE ROW LEVEL SECURITY for a single table,
 * then DROP IF EXISTS + CREATE the tenant_isolation policy.
 *
 * Using DROP + CREATE (instead of CREATE OR REPLACE) because PostgreSQL
 * does not support OR REPLACE for POLICY. The drop is always guarded with
 * IF EXISTS so this is safe to re-run.
 */
export function buildTablePolicyBlock(tableName: string): string {
  return [
    `ALTER TABLE ${tableName} ENABLE ROW LEVEL SECURITY;`,
    `ALTER TABLE ${tableName} FORCE ROW LEVEL SECURITY;`,
    `DROP POLICY IF EXISTS tenant_isolation ON ${tableName};`,
    `CREATE POLICY tenant_isolation ON ${tableName}`,
    `  USING      (${TENANT_PREDICATE})`,
    `  WITH CHECK (${TENANT_PREDICATE});`,
  ].join('\n');
}

/**
 * Generates a complete, runnable SQL string that enforces tenant isolation
 * on all tenant-scoped tables in the registry.
 *
 * The output is wrapped in BEGIN/COMMIT so it is transactional.
 */
export function buildTenantIsolationSql(): string {
  const blocks = TENANT_SCOPED_TABLES.map((entry) => {
    const header = `-- ${entry.name}${entry.notes ? ': ' + entry.notes : ''}`;
    return `${header}\n${buildTablePolicyBlock(entry.name)}`;
  });

  return [
    '-- Generated by packages/db/src/rls/policy-builder.ts',
    '-- DO NOT EDIT: re-generate via `pnpm --filter @opsninja/db build:rls`',
    '',
    'BEGIN;',
    '',
    blocks.join('\n\n'),
    '',
    'COMMIT;',
    '',
  ].join('\n');
}

/**
 * Returns the list of tenant-scoped table names, suitable for iterating in
 * tests to assert that every table has RLS enabled.
 */
export function getTenantScopedTableNames(): string[] {
  return TENANT_SCOPED_TABLES.map((t) => t.name);
}

/**
 * Returns the expected app_user grants for a given table, or undefined when
 * the table is not in the registry.
 */
export function getExpectedGrants(tableName: string): ReadonlyArray<string> | undefined {
  const entry = TENANT_SCOPED_TABLES.find((t) => t.name === tableName);
  return entry?.appUserGrants;
}
